### ISSUE TITLE
Screenshots not matching with Markbot

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/more-than-just-datum#1]
Hi @muxlowc,

I'm experiencing a weird issue with this assignment when I run it through Markbot. While in my browser, the header portion looks properly spaced compared to the screenshots provided in the Atom assignment. However, when I run the assignment through Markbot it looks like there's been padding added to the top and bottom of the header (but there's no padding in my code), therefore it deems the screenshots too visually different. I've attached a few images to hopefully better explain the issue I'm encountering, and I was wondering if you had any advice as to changes I could make to make the screenshots more similar. 

In the screenshots I provided below, my browser webpage is on the left, with the side-by-side Markbot comparisons on the right.

Thanks,
Rianna

<img width="937" alt="Screen Shot 2020-03-19 at 3 35 37 PM" src="https://user-images.githubusercontent.com/55094049/77108345-64abad80-69f8-11ea-9e42-5f0654049240.png">
<img width="1069" alt="Screen Shot 2020-03-19 at 3 35 46 PM" src="https://user-images.githubusercontent.com/55094049/77108350-65dcda80-69f8-11ea-913a-6edb474419d1.png">
<img width="626" alt="Screen Shot 2020-03-19 at 3 35 17 PM" src="https://user-images.githubusercontent.com/55094049/77108371-6f664280-69f8-11ea-9a70-5781ccd72f7c.png">
<img width="777" alt="Screen Shot 2020-03-19 at 3 36 19 PM" src="https://user-images.githubusercontent.com/55094049/77108389-768d5080-69f8-11ea-8f0f-885d27ca3a01.png">
<img width="1217" alt="Screen Shot 2020-03-19 at 3 37 15 PM" src="https://user-images.githubusercontent.com/55094049/77108392-78571400-69f8-11ea-9b54-b6a793bade08.png">

**Comment by muxlowc** [comment]
@riannazandbelt  I switched around a few things for you:

1) switch your h1 tag to surround your logo since it's the most important information on the page
2) surround your h1 tag with a div and switch over your unit / unit sizing
3) add the img-flex class to your logo image

```
<div class="unit xs-2-3 s-1-2 m-1-3 l-1-3 push-1-4 pad-t-1-8">
  <h1 class="push-0 logo"><img class="img-flex" src="images/logo.svg" alt=""></h1>
</div>
```

--
Just make sure to change what you have as your H1 right now to an H2. 
Once you switch this over, i think you just need a bit more padding to pass markbot
